### ISSUE TITLE
(Design) Text is cut off

### ISSUE THREAD

**Issue by mdp-dev** [EmanAzab/teaCozy#2]
When I tested this the text for locations were getting cut off on both sides - align left so that it breaks consistently.

https://github.com/EmanAzab/teaCozy/blob/ae02bffc637de5065cb5a826a153ed8b41597784/index.html#L63-L86

**Comment by EmanAzab** [comment]
I do some modifications, can you check them?!

**Comment by mdp-dev** [comment]
Nice! Way to iterate on your work
