### ISSUE TITLE
(Missing spec) No flexboxes

### ISSUE THREAD

**Issue by mdp-dev** [EmanAzab/teaCozy#3]
The exercise called for flexboxes, but there don't seem to be any in your documents. Try changing some of your containers to flex - such as this one:

https://github.com/EmanAzab/teaCozy/blob/ae02bffc637de5065cb5a826a153ed8b41597784/index.html#L22

**Comment by EmanAzab** [comment]
Sorry but it is already display: flex;

**Comment by mdp-dev** [comment]
Ah I see - you used a different naming convention than most student submissions and I overlooked your implementation in the CSS. Apologies!

Closing all - again, nice work!
